---
services:
    app:
        build:
            context: etc/php
            dockerfile: Dockerfile
        hostname: app
        container_name: test_app
        working_dir: "/app"
        volumes:
            - ".:/app"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini:ro"
        depends_on:
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    redis:
        image: redis:7.2-alpine3.19
        hostname: redis-db
        container_name: test_redis
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"
