---
services:
    app:
        build:
            context: etc/php
            dockerfile: Dockerfile
#        image: php:8.3-cli-alpine3.19
        hostname: app
        container_name: test_app
#        command: "tail -f /dev/null"
        working_dir: "/app"
        volumes:
            - ".:/app"
            # TODO: php custom config
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini:ro"
        depends_on:
            - redis
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    redis:
        image: redis:7.2-alpine3.19
        hostname: redis-db
        container_name: test_redis
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"
